/**
 * E2E Language Select APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  CrmV3ObjectsContactsResponse,
  crmV3ObjectsContactsResponseSchema,
} from '../models/crmV3ObjectsContactsResponse.js';
import { BaseController } from './baseController.js';

export class ApiController extends BaseController {
  /**
   * @return Response from the API call
   */
  async listContacts(
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<CrmV3ObjectsContactsResponse>> {
    const req = this.createRequest('GET', '/crm/v3/objects/contacts');
    req.authenticate([{ oAuth2: true }]);
    return req.callAsJson(crmV3ObjectsContactsResponseSchema, requestOptions);
  }
}
