/**
 * E2E Language Select APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

export interface Contact {
  id?: string;
  email?: string;
}

export const contactSchema: Schema<Contact> = object({
  id: ['id', optional(string())],
  email: ['email', optional(string())],
});
