/**
 * E2E Language Select APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema.js';
import { Contact, contactSchema } from './contact.js';

export interface CrmV3ObjectsContactsResponse {
  results?: Contact[];
}

export const crmV3ObjectsContactsResponseSchema: Schema<CrmV3ObjectsContactsResponse> = lazy(
  () => object({ results: ['results', optional(array(contactSchema))] })
);
