/**
 * E2E Language Select APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for OAuthScope
 */
export enum OAuthScope {
  CrmObjectsContactsRead = 'crm.objects.contacts.read',
}

/**
 * Schema for OAuthScope
 */
export const oAuthScopeSchema: Schema<OAuthScope> = stringEnum(OAuthScope);
